"""Alterando tipo da coluna chave_pix em pagamento

Revision ID: 180ed05abd2d
Revises: 7023bafa8e21
Create Date: 2025-03-14 17:19:44.846512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180ed05abd2d'
down_revision = '7023bafa8e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.alter_column('chave_pix',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.alter_column('chave_pix',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
