"""Adicioando Tabela Pix

Revision ID: 307718f820bd
Revises: 87d6043d70c2
Create Date: 2025-03-13 13:48:36.893800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307718f820bd'
down_revision = '87d6043d70c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pixes')
    # ### end Alembic commands ###
