"""Adicionando relacionamento entre Pix e Pagamento

Revision ID: 7023bafa8e21
Revises: 307718f820bd
Create Date: 2025-03-14 16:53:39.051058

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7023bafa8e21"
down_revision = "307718f820bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pagamentos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chave_pix", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("pix_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_pagamento_pix", "pixes", ["pix_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pagamentos", schema=None) as batch_op:
        batch_op.drop_constraint("fk_pagamento_pix", type_="foreignkey")
        batch_op.drop_column("pix_id")
        batch_op.drop_column("chave_pix")

    # ### end Alembic commands ###
